Repository NCAR/DART, pull requests merged in 2024-03, with the labels that each got.

#635 New interface to the Aether lat-lon model
  .gitignore
  CHANGELOG.rst
  assimilation_code/modules/utilities/netcdf_utilities_mod.f90
  conf.py
  index.rst
  models/aether_lat-lon/aether_to_dart.f90
  models/aether_lat-lon/dart_to_aether.f90
  models/aether_lat-lon/model_mod.f90
  models/aether_lat-lon/model_mod.nml
  models/aether_lat-lon/readme.rst
  models/aether_lat-lon/transform_state.nml
  models/aether_lat-lon/transform_state_mod.f90
  models/aether_lat-lon/work/filter_inputs.txt
  models/aether_lat-lon/work/filter_outputs.txt
  models/aether_lat-lon/work/input.nml
  models/aether_lat-lon/work/obs_seq.out.1
  models/aether_lat-lon/work/quickbuild.sh
Labels: Enhancement

#640 MITgcm/N-BLING with Compressed Staggered Grids
  CHANGELOG.rst
  assimilation_code/programs/model_mod_check/model_mod_check.f90
  conf.py
  models/MITgcm_ocean/model_mod.f90
  models/MITgcm_ocean/model_mod.nml
  models/MITgcm_ocean/readme.rst
  models/MITgcm_ocean/trans_mitdart_mod.f90
  models/MITgcm_ocean/work/input.nml
Labels: release!

#651 update bug report template to have Derecho not Cheyenne
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: release!

#637 Remove calls to no-op routines in ensemble manager
  assimilation_code/modules/assimilation/assim_tools_mod.pf.f90
  assimilation_code/modules/assimilation/filter_mod.dopplerfold.f90
  assimilation_code/modules/assimilation/filter_mod.f90
  assimilation_code/modules/assimilation/obs_model_mod.f90
  assimilation_code/modules/observations/forward_operator_mod.f90
  assimilation_code/modules/utilities/ensemble_manager_mod.f90
  assimilation_code/modules/utilities/ensemble_manager_mod.rst
  assimilation_code/programs/integrate_model/integrate_model.f90
  assimilation_code/programs/perfect_model_obs/perfect_model_obs.f90
Labels: release!

#636 Update WRF scripting and tutorial for derecho
  .github/ISSUE_TEMPLATE/bug_report.md
  CHANGELOG.rst
  assimilation_code/modules/assimilation/assim_tools_mod.pf.f90
  assimilation_code/modules/assimilation/filter_mod.dopplerfold.f90
  assimilation_code/modules/assimilation/filter_mod.f90
  assimilation_code/modules/assimilation/obs_model_mod.f90
  assimilation_code/modules/observations/forward_operator_mod.f90
  assimilation_code/modules/utilities/ensemble_manager_mod.f90
  assimilation_code/modules/utilities/ensemble_manager_mod.rst
  assimilation_code/programs/integrate_model/integrate_model.f90
  assimilation_code/programs/perfect_model_obs/perfect_model_obs.f90
  conf.py
  models/wrf/shell_scripts/assim_advance.csh
  models/wrf/shell_scripts/assimilate.csh
  models/wrf/shell_scripts/driver.csh
  models/wrf/shell_scripts/first_advance.csh
  models/wrf/shell_scripts/gen_retro_icbc.csh
  models/wrf/shell_scripts/init_ensemble_var.csh
  models/wrf/shell_scripts/param.csh
  models/wrf/shell_scripts/real.csh
  models/wrf/tutorial/README.rst
  models/wrf/tutorial/template/input.nml.template
Labels: Derecho, wrf, release!

#658 Create citation.cff for DART
  CITATION.cff
Labels: release!

#638 Recent WRF-Hydro Developments
  models/wrf_hydro/create_identity_streamflow_obs.f90
  models/wrf_hydro/hydro_dart_py/hydrodartpy/core/create_usgs_daily_obs_seq.py
  models/wrf_hydro/hydro_dart_py/hydrodartpy/core/setup_usgs_daily.py
  models/wrf_hydro/matlab/HydroDARTdiags.m
  models/wrf_hydro/model_mod.f90
  models/wrf_hydro/noah_hydro_mod.f90
  models/wrf_hydro/pmo/gauges.sh
  models/wrf_hydro/pmo/gen_truth.sh
  models/wrf_hydro/pmo/pmo_osse.py
Labels: release!

#639 Airs converter docs
  CHANGELOG.rst
  CITATION.cff
  conf.py
  models/wrf_hydro/create_identity_streamflow_obs.f90
  models/wrf_hydro/hydro_dart_py/hydrodartpy/core/create_usgs_daily_obs_seq.py
  models/wrf_hydro/hydro_dart_py/hydrodartpy/core/setup_usgs_daily.py
  models/wrf_hydro/matlab/HydroDARTdiags.m
  models/wrf_hydro/model_mod.f90
  models/wrf_hydro/noah_hydro_mod.f90
  models/wrf_hydro/pmo/gauges.sh
  models/wrf_hydro/pmo/gen_truth.sh
  models/wrf_hydro/pmo/pmo_osse.py
  observations/obs_converters/AIRS/BUILD_HDF-EOS.sh
  observations/obs_converters/AIRS/L1_AMSUA_to_netcdf.f90
  observations/obs_converters/AIRS/README.rst
  observations/obs_converters/AIRS/airs_JPL_mod.f90
  observations/obs_converters/AIRS/airs_obs_mod.f90
  observations/obs_converters/AIRS/convert_airs_L2.nml
  observations/obs_converters/AIRS/convert_airs_L2.rst
  observations/obs_converters/AIRS/convert_amsu_L1.rst
  observations/obs_converters/AIRS/shell_scripts/Build_HDF_to_netCDF.sh
  observations/obs_converters/AIRS/shell_scripts/Convert_HDF_to_netCDF.csh
  observations/obs_converters/AIRS/shell_scripts/README
  observations/obs_converters/AIRS/shell_scripts/download_L2.sh
  observations/obs_converters/AIRS/shell_scripts/oneday_down.sh
  observations/obs_converters/AIRS/work/input.nml
  observations/obs_converters/AIRS/work/quickbuild.sh
  observations/obs_converters/gps/gps.rst
Labels: release!
