Repository NCAR/DART, pull requests merged in 2024-01, with the labels that each got.

#605 Update filter_mod.rst
  assimilation_code/modules/assimilation/filter_mod.f90
  assimilation_code/modules/assimilation/filter_mod.rst
Labels: release!

#618 fix: format statement in assert_mod
  assimilation_code/modules/utilities/assert_mod.f90
Labels: release!

#617 remove register for dart link because this no longer exists
  README.md
  models/wrf/tutorial/README.rst
Labels: release!

#623 Correct CLM-DART sourcemod path
  models/clm/shell_scripts/cesm2_2/DART_params.csh
Labels: CLM, Derecho

#606 bug-fix: CCE compiler error and warnings for dart_to_clm variable snlsno
  CHANGELOG.rst
  conf.py
  models/clm/dart_to_clm.f90
  models/clm/shell_scripts/cesm2_2/DART_params.csh
Labels: fortran standards
