Repository NCAR/DART, pull requests merged in 2025-05, with the labels that each got.

#863 bug-fixes: small bugs in the bnrh_distribution_mod.f90
  assimilation_code/modules/assimilation/bnrh_distribution_mod.f90
Labels: release!

#865 fix doc namelist name for perturb_single_instance
  assimilation_code/programs/perturb_single_instance/perturb_single_instance.rst
Labels: release!

#852 fix: vtec extrapolation calculation in TIEGCM
  CHANGELOG.rst
  conf.py
  models/tiegcm/model_mod.f90
Labels: release!, tiegcm

#869 Updated CONAGUA readme
  observations/obs_converters/CONAGUA/README.rst
Labels: release!

#854 Updated radar observation docs
  observations/obs_converters/radar/README.rst
Labels: Documentation, wrf, release!

#850 Freeboard fwd operator for radar, laser
  CHANGELOG.rst
  conf.py
  observations/forward_operators/obs_def_cice_mod.f90
Labels: release!, cice
