Repository NCAR/DART, pull requests merged in 2025-02, with the labels that each got.

#806 Updated Inflation Documentation
  guide/images/loc_types.png
  guide/images/science_nuggets/prior_poste_inf_l63.png
  guide/important-capabilities-dart.rst
  guide/inflation.rst
Labels: release!

#821 doc-fix: heading hierarchy for Forward Operators section
  guide/forward_operator.rst
Labels: release!

#776 Check list of state variables for required ones
  CHANGELOG.rst
  conf.py
  guide/forward_operator.rst
  models/cam-fv/model_mod.f90
  models/cam-se/model_mod.f90
  models/cam-se/model_mod.nml
  models/cam-se/work/input.nml
Labels: Bug, Minor, CAM, release!, CAM-SE

#783 Generalized subroutine to read the state variables from the namelist (parse_variables)
  .gitignore
  CHANGELOG.rst
  assimilation_code/modules/io/state_structure_mod.f90
  conf.py
  developer_tests/namelist/test_parse_variables.f90
  developer_tests/namelist/work/input.nml
  developer_tests/namelist/work/quickbuild.sh
  models/MOM6/model_mod.f90
  models/POP/model_mod.f90
  models/aether_lat-lon/model_mod.f90
  models/cam-common-code/cam_common_code_mod.f90
  models/cam-fv/model_mod.f90
  models/cam-se/model_mod.f90
  models/cice/model_mod.f90
  models/template/threed_model_mod.f90
  models/template/work/threed_input.nml
  models/utilities/default_model_mod.f90
  models/wrf_hydro/model_mod.f90
Labels: release!

#823 Updating WRF-DART tutorial obs converter doc and NCEP Prepbufr converter docs
  CHANGELOG.rst
  conf.py
  guide/creating-obs-seq-real.rst
  models/wrf/readme.rst
  models/wrf/tutorial/README.rst
  observations/obs_converters/NCEP/prep_bufr/prep_bufr.rst
Labels: Documentation, Derecho, wrf
