Repository NCAR/DART, pull requests merged in 2025-01, with the labels that each got.

#785 Notify user if using RTPS inflation that QCEFF options ignored for posterior inflation
  assimilation_code/modules/assimilation/filter_mod.f90
  guide/qceff_probit.rst
Labels: release!

#791 Modified oned/obs_diag.f90 to add an unused singleton level
  CHANGELOG.rst
  assimilation_code/programs/obs_diag/oned/obs_diag.f90
  conf.py
Labels: release!

#793 fix lorenz_93 and lorenz_63 workshop input.nmls to have v11 version of namelist
  models/lorenz_63/work/input.workshop.nml
  models/lorenz_96/work/input.workshop.nml
Labels: release!

#782 fix: potential temp to temp conversion for MOM6 model_interpolate
  CHANGELOG.rst
  conf.py
  models/MOM6/model_mod.f90
Labels: release!, mom6

#795 Remove test_obs directory - not used (built or run)
  observations/obs_converters/test_obs/make_fake_obs.f90
  observations/obs_converters/test_obs/threed_sphere/input.nml
  observations/obs_converters/test_obs/threed_sphere/make_fake_obs.nml
Labels: release!, dead-code

#790 Updated RDA addresses and dataset names
  conf.py
  guide/references.rst
  guide/requirements.txt
  index.rst
  models/POP/readme.rst
  models/POP/shell_scripts/cesm2_1/user_datm.streams.txt.CPLHISTForcing.Solar_template
  models/POP/shell_scripts/cesm2_1/user_datm.streams.txt.CPLHISTForcing.State1hr_template
  models/POP/shell_scripts/cesm2_1/user_datm.streams.txt.CPLHISTForcing.State3hr_template
  models/POP/shell_scripts/cesm2_1/user_datm.streams.txt.CPLHISTForcing.nonSolarFlux_template
  models/cam-fv/readme.rst
  models/cice/shell_scripts/CESM1_5_setup_ensemble
  models/cice/shell_scripts/datm.streams.txt.CPLHIST3HrWx.Precip_template
  models/cice/shell_scripts/datm.streams.txt.CPLHIST3HrWx.Solar_template
  models/cice/shell_scripts/datm.streams.txt.CPLHIST3HrWx.nonSolarNonPrecip_template
  models/cice/shell_scripts/datm.streams.txt.CPLHISTForcing.Solar_2005to2010
  models/cice/shell_scripts/datm.streams.txt.CPLHISTForcing.Solar_complete
  models/cice/shell_scripts/datm.streams.txt.CPLHISTForcing.Solar_single
  models/cice/shell_scripts/datm.streams.txt.CPLHISTForcing.Solar_template
  models/cice/shell_scripts/datm.streams.txt.CPLHISTForcing.State1hr_2005to2010
  models/cice/shell_scripts/datm.streams.txt.CPLHISTForcing.State1hr_complete
  models/cice/shell_scripts/datm.streams.txt.CPLHISTForcing.State1hr_single
  models/cice/shell_scripts/datm.streams.txt.CPLHISTForcing.State1hr_template
  models/cice/shell_scripts/datm.streams.txt.CPLHISTForcing.State3hr_2005to2010
  models/cice/shell_scripts/datm.streams.txt.CPLHISTForcing.State3hr_3hr
  models/cice/shell_scripts/datm.streams.txt.CPLHISTForcing.State3hr_complete
  models/cice/shell_scripts/datm.streams.txt.CPLHISTForcing.State3hr_single
  models/cice/shell_scripts/datm.streams.txt.CPLHISTForcing.State3hr_template
  models/cice/shell_scripts/datm.streams.txt.CPLHISTForcing.nonSolarFlux_2005to2010
  models/cice/shell_scripts/datm.streams.txt.CPLHISTForcing.nonSolarFlux_3hr
  models/cice/shell_scripts/datm.streams.txt.CPLHISTForcing.nonSolarFlux_complete
  models/cice/shell_scripts/datm.streams.txt.CPLHISTForcing.nonSolarFlux_single
  models/cice/shell_scripts/datm.streams.txt.CPLHISTForcing.nonSolarFlux_template
  models/clm/CAM_bias_correction/CAM4_site_grid.sh
  models/clm/CAM_bias_correction/CAM6_site_grid.sh
  models/clm/CAM_bias_correction/README
  models/clm/matlab/CheckDATM.m
  models/clm/shell_scripts/cesm1_x/CESM1_1_1_setup_hybrid
  models/clm/shell_scripts/cesm1_x/CESM1_1_1_setup_pmo
  models/clm/shell_scripts/cesm1_x/CESM1_2_1_setup_hybrid
  models/clm/shell_scripts/cesm2_2/DART_params.csh
  models/clm/shell_scripts/cesm2_2/datm.streams.txt.CPLHISTForcing.Solar_complete
  models/clm/shell_scripts/cesm2_2/datm.streams.txt.CPLHISTForcing.Solar_single_year
  models/clm/shell_scripts/cesm2_2/datm.streams.txt.CPLHISTForcing.State1hr_complete
  models/clm/shell_scripts/cesm2_2/datm.streams.txt.CPLHISTForcing.State1hr_single_year
  models/clm/shell_scripts/cesm2_2/datm.streams.txt.CPLHISTForcing.State3hr_complete
  models/clm/shell_scripts/cesm2_2/datm.streams.txt.CPLHISTForcing.State3hr_single_year
  models/clm/shell_scripts/cesm2_2/datm.streams.txt.CPLHISTForcing.nonSolarFlux_complete
  models/clm/shell_scripts/cesm2_2/datm.streams.txt.CPLHISTForcing.nonSolarFlux_single_year
  models/clm/tutorial/README.rst
  models/wrf/tutorial/README.rst
  observations/obs_converters/NCEP/prep_bufr/prep_bufr.rst
  observations/obs_converters/WOD/WOD.rst
Labels: Bug, Documentation, CAM, CLM, wrf, release!, POP, cice

#794 Qceff inflation fix; Explicitly handling BNRHF transform failures.
  CHANGELOG.rst
  assimilation_code/modules/assimilation/assim_tools_mod.f90
  assimilation_code/modules/assimilation/filter_mod.f90
  assimilation_code/modules/assimilation/probit_transform_mod.f90
  conf.py
Labels: Critical
