Repository NCAR/DART, pull requests merged in 2025-07, with the labels that each got.

#901 set ieee for cce compiler in mkmf.tempate
  build_templates/mkmf.template.cce
Labels: release!

#883 Documentation for namelist options for data management and vertical conversion temporal choice
  CHANGELOG.rst
  assimilation_code/modules/assimilation/assim_tools_mod.rst
  assimilation_code/modules/utilities/ensemble_manager_mod.rst
  conf.py
  guide/data-management-issues.rst
  guide/forward_operator.rst
  guide/vertical-conversion.rst
Labels: Documentation, release!

#919 Use new container for github action-on-pull
  .github/actions/build_run_model/action.yml
  .github/workflows/action_on_pull_request.yml
Labels: release!

#916 bug-fix: perfect_model_obs prints
  assimilation_code/programs/perfect_model_obs/perfect_model_obs.f90
Labels: release!

#858 Addition of improved MODIS ice surface temperature observation converter program
  .gitignore
  guide/available-observation-converters.rst
  index.rst
  observations/obs_converters/MODIS/MOD29E1D_to_obs.f90
  observations/obs_converters/MODIS/MOD29E1D_to_obs.nml
  observations/obs_converters/MODIS/MOD29E1D_to_obs.rst
  observations/obs_converters/MODIS/data/MOD29E1D_2000_02_24.EXAMPLE.hdf
  observations/obs_converters/MODIS/readme.rst
  observations/obs_converters/MODIS/shell_scripts/MOD29E1D_hdf_to_netcdf.py
  observations/obs_converters/MODIS/work/input.nml
  observations/obs_converters/MODIS/work/quickbuild.sh
  observations/obs_converters/README.rst
  observations/obs_converters/cice/modis_ist_to_obs_netcdf.f90
  observations/obs_converters/cice/modis_ist_to_obs_netcdf.nml
Labels: release!, cice

#931 MOM6: correct u grid for get_interp_handle, correct distance when there are land points in get_close_state
  CHANGELOG.rst
  conf.py
  models/MOM6/model_mod.f90
  models/MOM6/readme.rst
Labels: release!, mom6
